package UI;

import java.awt.Image;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import logicBusiness.Login;

/*
 * @author ANONYMOUS
 * @author JULIAN C
 * @author DANIEL R
 * @author JUAN B
 */
public class LoginScreen extends javax.swing.JFrame {

    /*
     * Creates new form Login
     */
    private final Login login = new Login();
    private String user = "", password = "";
    private int failedAttempt = 0;

    public LoginScreen() {
        initComponents();
        setLocationRelativeTo(null); //To center window
        setResizable(false);
        //jLabelLogin.setText("Hola");
        setIconImage(new ImageIcon(getClass().getResource("/resources/img/icono.jpg")).getImage());

        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon background = new ImageIcon(this.getClass().getResource("/resources/img/logotipoV.jpg"));

        background = new ImageIcon(background.getImage().getScaledInstance(getWidth() / 2, 350,
                Image.SCALE_SMOOTH));

        JLabel fondo = new JLabel();
        fondo.setIcon(background);

        getLayeredPane().add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(30, 30, background.getIconWidth(), background.getIconHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLoginBox = new javax.swing.JPanel();
        titleBox_jPanel = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jPanelUserPassBox = new javax.swing.JPanel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        txtPasswordField = new javax.swing.JPasswordField();
        txtUser = new javax.swing.JTextField();
        btnSignUp = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelErrorLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLoginBox.setOpaque(false);

        titleBox_jPanel.setBackground(new java.awt.Color(102, 255, 102));

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelLogin.setText("Iniciar Sesión");

        javax.swing.GroupLayout titleBox_jPanelLayout = new javax.swing.GroupLayout(titleBox_jPanel);
        titleBox_jPanel.setLayout(titleBox_jPanelLayout);
        titleBox_jPanelLayout.setHorizontalGroup(
            titleBox_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBox_jPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabelLogin)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        titleBox_jPanelLayout.setVerticalGroup(
            titleBox_jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBox_jPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabelLogin)
                .addContainerGap())
        );

        jPanelUserPassBox.setBackground(new java.awt.Color(204, 204, 204));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUsuario.setText("Usuario:");

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPassword.setText("Contraseña:");

        txtPasswordField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPasswordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordFieldKeyPressed(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        txtUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelUserPassBoxLayout = new javax.swing.GroupLayout(jPanelUserPassBox);
        jPanelUserPassBox.setLayout(jPanelUserPassBoxLayout);
        jPanelUserPassBoxLayout.setHorizontalGroup(
            jPanelUserPassBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserPassBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserPassBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jLabelPassword)
                    .addComponent(txtPasswordField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelUserPassBoxLayout.setVerticalGroup(
            jPanelUserPassBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserPassBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelUsuario)
                .addGap(18, 18, 18)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabelPassword)
                .addGap(18, 18, 18)
                .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnSignUp.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSignUp.setText("Registrarse");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnLogIn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogIn.setText("Iniciar Sesión");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelErrorLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelErrorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelLoginBoxLayout = new javax.swing.GroupLayout(jPanelLoginBox);
        jPanelLoginBox.setLayout(jPanelLoginBoxLayout);
        jPanelLoginBoxLayout.setHorizontalGroup(
            jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLoginBoxLayout.createSequentialGroup()
                .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                        .addGap(0, 468, Short.MAX_VALUE)
                        .addComponent(titleBox_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSignUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelUserPassBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
        );
        jPanelLoginBoxLayout.setVerticalGroup(
            jPanelLoginBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleBox_jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanelUserPassBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSignUp)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jPanelLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanelLoginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        UserRegisterScreen ur = new UserRegisterScreen();
        ur.setVisible(true);
        ur.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        //BORRAR
        
        PrincipalScreen pScreen = new PrincipalScreen();
        pScreen.setVisible(true);
        this.setVisible(false);
        //BORRAR SOLO PRUEBA*/
        
        user = txtUser.getText();
        user = user.replaceAll(" ", "").trim().toLowerCase();
        password = new String(txtPasswordField.getPassword());

        if ((user.equals("")) && (password.equals(""))) {
            jLabelErrorLogin.setText("*Los campos no pueden estar vacíos");
            //JOptionPane.showMessageDialog(rootPane, "Los campos no pueden estar vacíos");
        } else {

            try {
                login.logIn(user, password);
            } catch (Exception ex) {
                Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (login.isActiveSession() == true) {
                setVisible(false);
                failedAttempt = 0;
                PrincipalScreen ps = new PrincipalScreen();
                ps.setVisible(true);

            } else if (login.isThereIsAUser() == false) {
                failedAttempt++;
                jLabelErrorLogin.setText("*Usuario y/o contraseña errados");
                if (failedAttempt > 2) {
                    JOptionPane.showMessageDialog(rootPane, "Si no tiene una cuenta,\n resgistrese por favor.");
                    setVisible(false);
                    UserRegisterScreen ur = new UserRegisterScreen();
                    ur.setVisible(true);
                    ur.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                }
            } else {
                jLabelErrorLogin.setText("*Usuario y/o contraseña errados");
                //JOptionPane.showMessageDialog(null, "Usuario y/o contraseña errados");
                System.out.println("Usuario y/o contraseña errados");
                txtUser.requestFocus();
                txtUser.setText("");
                txtPasswordField.setText("");
                failedAttempt = 0;
            }

        }
    }//GEN-LAST:event_btnLogInActionPerformed

    private void txtUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserKeyPressed
        // TODO add your handling code here:
        char nextTextField = (char) evt.getKeyCode();
        if (nextTextField == evt.VK_ENTER) {
            this.txtPasswordField.requestFocus();
        }
    }//GEN-LAST:event_txtUserKeyPressed

    private void txtPasswordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordFieldKeyPressed
        char validate = (char) evt.getKeyCode();
        if (validate == evt.VK_ENTER) {

            user = txtUser.getText();
            user = user.replaceAll(" ", "").trim().toLowerCase();
            password = new String(txtPasswordField.getPassword());

            if ((user.equals("")) && (password.equals(""))) {
                jLabelErrorLogin.setText("*Los campos no pueden estar vacíos");
                //JOptionPane.showMessageDialog(rootPane, "Los campos no pueden estar vacíos");
            } else {

                try {
                    login.logIn(user, password);
                } catch (Exception ex) {
                    Logger.getLogger(LoginScreen.class.getName()).log(Level.SEVERE, null, ex);
                }

                if (login.isActiveSession() == true) {
                    setVisible(false);
                    failedAttempt = 0;
                    PrincipalScreen ps = new PrincipalScreen();
                    ps.setVisible(true);
                } else if (login.isThereIsAUser() == false) {
                    failedAttempt++;
                    jLabelErrorLogin.setText("*Usuario y/o contraseña errados");
                    if (failedAttempt > 2) {
                        JOptionPane.showMessageDialog(rootPane, "Si no tiene una cuenta,\n resgistrese por favor.");
                        setVisible(false);
                        UserRegisterScreen ur = new UserRegisterScreen();
                        ur.setVisible(true);
                        ur.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                    }
                } else {
                    jLabelErrorLogin.setText("*Usuario y/o contraseña errados");
                    //JOptionPane.showMessageDialog(null, "Usuario y/o contraseña errados");
                    System.out.println("Usuario y/o contraseña errados");
                    txtUser.requestFocus();
                    txtUser.setText("");
                    txtPasswordField.setText("");
                    failedAttempt = 0;
                }

            }

        }
    }//GEN-LAST:event_txtPasswordFieldKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });

    }//End main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel jLabelErrorLogin;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelLoginBox;
    private javax.swing.JPanel jPanelUserPassBox;
    private javax.swing.JPanel titleBox_jPanel;
    private javax.swing.JPasswordField txtPasswordField;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
