package UI;


import data.User;
import java.awt.Image;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import logicBusiness.Login;

/*
 * @author ANONYMOUS
 * @author JULIAN C
 * @author DANIEL R
 * @author JUAN B
 */
public class PatientPrincipalScreen extends javax.swing.JFrame {
   
    private final User users = new User();
    private final Login login = new Login();
    private HashMap<String, String[]> listOfPatients = new HashMap<>();
    private HashMap<String, String[]> loginList = new HashMap<>();
    private HashMap<String, String[]> patients = null;
    
    
    DefaultTableModel modelo;

    private String searchText = "";

    public PatientPrincipalScreen() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        double mesomorfia = 0;
        double endomorfia = 0;
        double ectomorfia = 0;
        double transformadaX = (270 + 37*(ectomorfia - endomorfia));
        double transformadaY = (180 + 12*(ectomorfia + endomorfia - mesomorfia));
        int posX = (int)transformadaX;
        int posY = (int)transformadaY;

        //loadPatient("");

        setIconImage(new ImageIcon(getClass().getResource("/resources/img/icono.jpg")).getImage());

        ((JPanel) getContentPane()).setOpaque(false);
        ImageIcon background = new ImageIcon(this.getClass().getResource("/resources/img/logotipoH.jpg"));

        background = new ImageIcon(background.getImage().getScaledInstance(getWidth() / 4, getHeight() / 8, Image.SCALE_SMOOTH));

        JLabel fondo = new JLabel();
        fondo.setIcon(background);

        jPanelBase.add(fondo, JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(550, 12, background.getIconWidth(), background.getIconHeight());
        
        // Resultado en somatotipo
        
        ImageIcon somatotip = new ImageIcon(this.getClass().getResource("/resources/img/Somatotipo.jpg"));

        somatotip = new ImageIcon(somatotip.getImage().getScaledInstance(600, 340, Image.SCALE_SMOOTH));

        JLabel somatotipScreen = new JLabel();
        somatotipScreen.setIcon(somatotip);

        jpanelScore.add(somatotipScreen, JLayeredPane.FRAME_CONTENT_LAYER);
        somatotipScreen.setBounds(0, 0, somatotip.getIconWidth(), somatotip.getIconHeight() );
        
        // Ubicador
        
        ImageIcon ubicador = new ImageIcon(this.getClass().getResource("/resources/img/ubicador.jpg"));

        ubicador = new ImageIcon(ubicador.getImage().getScaledInstance( 10, 10, Image.SCALE_SMOOTH));

        JLabel locator = new JLabel();
        locator.setIcon(ubicador);

        jpanelLocator.add(locator, JLayeredPane.FRAME_CONTENT_LAYER);
        locator.setBounds(posX, posY, ubicador.getIconWidth(),ubicador.getIconHeight() );
        
        
        try {
            users.readDatabase();
            login.readDatabase();
            listOfPatients = users.getListOfPatientData();
            loginList = login.getUserLoginList();

            String[] loginData = loginList.get(LoginScreen.getUser());
            String[] userData = listOfPatients.get(loginData[0]);

            //System.out.println("INFO USER: " + Arrays.toString(loginData) + Arrays.toString(userData));
            jLabelName.setText(userData[1] + " " + userData[2]);

            //txtLastnames.setText(userData[2]);
        } catch (Exception ex) {
            Logger.getLogger(EditUserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void loadPatient(String buscar) {
        
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelBase = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelUserType = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jPanelSignUpTitle = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpanelScore = new javax.swing.JPanel();
        jpanelLocator = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBase.setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelUserType.setBackground(new java.awt.Color(255, 204, 204));
        jLabelUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUserType.setText("PACIENTE");
        jLabelUserType.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelUserType.setOpaque(true);

        jLabelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelName.setText("Nombre");

        btnLogout.setBackground(new java.awt.Color(255, 204, 204));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnLogout.setText("Cerrar Sesión");
        btnLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelUserType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabelUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelSignUpTitle.setBackground(new java.awt.Color(0, 255, 102));

        jLabel3.setBackground(new java.awt.Color(102, 255, 102));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BODYMETRIC");

        javax.swing.GroupLayout jPanelSignUpTitleLayout = new javax.swing.GroupLayout(jPanelSignUpTitle);
        jPanelSignUpTitle.setLayout(jPanelSignUpTitleLayout);
        jPanelSignUpTitleLayout.setHorizontalGroup(
            jPanelSignUpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSignUpTitleLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel3)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanelSignUpTitleLayout.setVerticalGroup(
            jPanelSignUpTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSignUpTitleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jpanelLocator.setOpaque(false);

        javax.swing.GroupLayout jpanelLocatorLayout = new javax.swing.GroupLayout(jpanelLocator);
        jpanelLocator.setLayout(jpanelLocatorLayout);
        jpanelLocatorLayout.setHorizontalGroup(
            jpanelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 584, Short.MAX_VALUE)
        );
        jpanelLocatorLayout.setVerticalGroup(
            jpanelLocatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpanelScoreLayout = new javax.swing.GroupLayout(jpanelScore);
        jpanelScore.setLayout(jpanelScoreLayout);
        jpanelScoreLayout.setHorizontalGroup(
            jpanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelLocator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpanelScoreLayout.setVerticalGroup(
            jpanelScoreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelScoreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpanelLocator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBaseLayout = new javax.swing.GroupLayout(jPanelBase);
        jPanelBase.setLayout(jPanelBaseLayout);
        jPanelBaseLayout.setHorizontalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaseLayout.createSequentialGroup()
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanelSignUpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jpanelScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanelBaseLayout.setVerticalGroup(
            jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBaseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSignUpTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(jPanelBaseLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jpanelScore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBase, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginScreen lgScreen = new LoginScreen();
        lgScreen.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelUserType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBase;
    private javax.swing.JPanel jPanelSignUpTitle;
    private javax.swing.JPanel jpanelLocator;
    private javax.swing.JPanel jpanelScore;
    // End of variables declaration//GEN-END:variables
}
